import React, { FormEvent, useState } from "react";
import { Comment } from "../App";

interface CommentsProps {
  postId: string;
  comments: Comment[];
}

/**
 * TODO : Remove event: FormEvent preventDefault when I add backend
 * TODO : make insert comment on backend
 */
export default function CommentsSection({ postId, comments }: CommentsProps) {
  const [allComments, setAllComments] = useState(comments);
  const [newCommentContent, setNewCommentContent] = useState("");

  const getLoggedInUser = () => {
    const storedUser = localStorage.getItem("user");

    if (!storedUser) {
      return null;
    }

    try {
      return JSON.parse(storedUser); // Parse JSON safely
    } catch (error) {
      console.error("Error parsing user data:", error);
      return null;
    }
  };

  const loggedInUser = getLoggedInUser();

  const handlePostComment = async (event: FormEvent) => {
    event.preventDefault();

    if (!loggedInUser) {
      console.error("User is not logged in");
      return;
    }

    const formatDate = () => {
      const now = new Date();
      const year = now.getFullYear();
      const month = String(now.getMonth() + 1).padStart(2, "0");
      const day = String(now.getDate()).padStart(2, "0");
      const hours = String(now.getHours()).padStart(2, "0");
      const minutes = String(now.getMinutes()).padStart(2, "0");
      const seconds = String(now.getSeconds()).padStart(2, "0");

      return `${year}-${month}-${day} ${hours}:${minutes}:${seconds}`;
    };

    const newCommentBody: Comment = {
      id: "", // ID will be generated by the backend
      avatar: loggedInUser.avatar,
      name: loggedInUser.name,
      datePosted: formatDate(),
      content: newCommentContent,
      postId: postId,
      userId: loggedInUser.id, // Include the user's ID
    };

    try {
      const response = await fetch(
        `http://localhost:8080/insertCommentByPostId/${postId}/${loggedInUser.id}`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify(newCommentBody),
        }
      );

      if (!response.ok) {
        const errorResponse = await response.text();
        throw new Error(`Failed to post comment: ${errorResponse}`);
      }

      const message = await response.text();
      console.log(message);

      setAllComments([...allComments, newCommentBody]);
      setNewCommentContent("");
    } catch (error) {
      console.error("Error posting comment:", error);
    }
  };

  const handleDeleteComment = async (commentId: string) => {
    try {
      const response = await fetch(
        `http://localhost:8080/deleteComment/${commentId}`,
        { method: "DELETE" }
      );

      if (!response.ok) {
        const errorResponse = await response.text();
        throw new Error(`Failed to delete comment: ${errorResponse}`);
      }
      // Remove comment from the state
      setAllComments(allComments.filter((comment) => comment.id !== commentId));
    } catch (error) {
      console.error("Error deleting comment:", error);
    }
  };

  return (
    <section className="w-full py-8 lg:py-16 antialiased">
      <div className="max-w-2xl mx-auto px-4">
        <div className="flex justify-between items-center mb-6">
          <h2 className="text-lg lg:text-2xl font-bold text-gray-900">
            Discussion ({allComments.length})
          </h2>
        </div>
        <form className="mb-6" onSubmit={handlePostComment}>
          <div className="py-2 px-4 mb-4 bg-blue-300 rounded-lg rounded-t-lg">
            <label htmlFor="comment" className="sr-only">
              Your comment
            </label>
            <textarea
              id="comment"
              className="px-0 w-full bg-blue-300 text-sm text-gray-900 border-0 focus:ring-0 focus:outline-none"
              placeholder="Write a comment..."
              required
              value={newCommentContent}
              onChange={(e) => setNewCommentContent(e.target.value)}
            ></textarea>
          </div>
          <button
            type="submit"
            className="edit-button top-4 right-4 bg-sky-800 text-white px-5 py-1 mb-2 mr-2 rounded"
          >
            Post comment
          </button>
        </form>
        {allComments.map((comment) => (
          <article
            key={comment.id}
            className="p-6 text-base bg-blue-300 rounded-lg my-2"
          >
            <footer className="flex justify-between items-center mb-2">
              <div className="flex items-center">
                <p className="inline-flex items-center mr-3 text-sm text-gray-900 font-semibold">
                  <img
                    className="mr-2 w-6 h-6 rounded-full"
                    src={comment.avatar}
                    alt={comment.name}
                  />
                  {comment.name}
                </p>
                <p className="text-sm text-gray-600">
                  <time title={comment.datePosted}>{comment.datePosted}</time>
                </p>
              </div>
              {comment.userId === loggedInUser?.id && (
                <button
                  className="text-red-500 text-sm"
                  onClick={() => handleDeleteComment(comment.id)}
                >
                  Delete
                </button>
              )}
            </footer>
            <p className="text-gray-700">{comment.content}</p>
          </article>
        ))}
      </div>
    </section>
  );
}
